---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - net-snmp
        - net-snmp-utils
        - net-snmp-devel
        - unzip
        
    - name: Configure SNMP v2c Community
      lineinfile:
      path: /etc/snmp/snmpd.conf
      regexp: 'com2sec notConfigUser  default       public'
      line: 'com2sec notConfigUser  default       NEWTESTSTRING'
      backrefs: true
      
    - name: Start SNMP Service
      service:
       name: snmpd
      state: started
      enabled: yes
   
